'use client'

import { motion } from 'framer-motion'
import AnimatedCounter from '../ui/AnimatedCounter'

const statCards = [
  {
    id: 'revenue',
    value: (
      <>
        $
        <AnimatedCounter end={1.4} decimals={1} />B
      </>
    ),
    description:
      'Estimated annual property-tax revenue generated by the data center project.',
    source: 'City financial model',
  },
  {
    id: 'investment',
    value: (
      <>
        $
        <AnimatedCounter end={900} />
        M+
      </>
    ),
    description:
      'Private investment committed to build and support the data center campus.',
    source: 'Project disclosures',
  },
  {
    id: 'taxes',
    value: '$0',
    description: 'No new taxes on families are required to fund the project.',
    source: 'Tax agreement',
  },
]
export default function TaxRevenue() {
  return (
    <section id='tax' className='bg-[#F7F3EC] py-24 lg:py-32 overflow-hidden'>
      <div className='max-w-250 mx-auto px-6'>
        {/* Header */}

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          viewport={{ once: true }}
        >
          <p
            className='
              uppercase
              tracking-[0.25em]
              text-[#C89A3E]
              text-xs
              font-bold
              mb-4
            '
          >
            Tax Revenue
          </p>

          <h2
            className='
              font-serif
              text-[#16352A]
              text-[clamp(2.2rem,5vw,3.8rem)]
              md:text-5xl
              font-bold
              leading-tight
              max-w-4xl
            '
          >
            Significant Revenue for Schools and City Services — Without New
            Taxes on Families
          </h2>

          <p
            className='
              mt-8
              text-[#3E3E3E]
              text-lg
              leading-8
              max-w-4xl
            '
          >
            Data centers generate major property-tax revenue with minimal demand
            on local public services. They do not bring population growth,
            traffic strain, or demands on schools, emergency services, or
            infrastructure — making every dollar of new revenue available for
            community priorities.
          </p>
        </motion.div>

        {/* Stats Cards */}

        <div className='grid md:grid-cols-3 gap-6 mt-14'>
          {statCards.map((card, index) => (
            <motion.div
              key={card.id}
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{
                duration: 0.6,
                delay: index * 0.1,
              }}
              viewport={{ once: true }}
              whileHover={{ y: -6 }}
              className='
                bg-white
                border-t-4
                border-[#C89A3E]
                shadow-sm
                p-8
              '
            >
              <div
                className='
                  font-serif
                  text-[3.2rem]
                  leading-none
                  font-bold
                  text-[#16352A]
                '
              >
                {card.value}
              </div>

              <p
                className='
                  mt-6
                  text-[#3E3E3E]
                  leading-8
                '
              >
                {card.description}
              </p>

              {card.source && (
                <p
                  className='
                    mt-5
                    text-sm
                    italic
                    text-[#7A7A7A]
                  '
                >
                  {card.source}
                </p>
              )}
            </motion.div>
          ))}
        </div>

        {/* Content Grid */}

        <div className='grid lg:grid-cols-2 gap-14 mt-16'>
          {/* Left Column */}

          <motion.div
            initial={{ opacity: 0, x: -40 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.7 }}
            viewport={{ once: true }}
            className='space-y-8'
          >
            <p className='text-[#3E3E3E] leading-8'>
              Property-tax revenue from large-scale data center development
              flows directly to local school budgets and city services. Unlike
              residential or commercial growth, data centers do not bring
              students to schools, increased demand for emergency services, or
              strain on roads and infrastructure.
            </p>

            <p className='text-[#3E3E3E] leading-8'>
              In Loudoun County, Virginia — the nation's leading data center
              market — data centers return{' '}
              <strong>
                $26 in local tax revenue for every $1 they require in county
                services.
              </strong>{' '}
              Rocky Mount's deal structure, with enforceable cost-accountability
              provisions, is designed to produce comparable returns without
              rate-shifting to existing residents.
            </p>

            <ul
              className='
                list-disc
                pl-6
                space-y-4
                text-[#3E3E3E]
                leading-8
              '
            >
              <li>
                New school budget dollars — for programs, teachers, and
                facilities — without raising taxes on working families.
              </li>

              <li>
                Developer-assigned grid-upgrade costs mean infrastructure
                improvements are paid by the company, not the community.
              </li>

              <li>
                Annual financial reconciliation reviewed and published — no
                hidden cost-shifting after approval.
              </li>
            </ul>
          </motion.div>

          {/* Right Column */}

          <motion.div
            initial={{ opacity: 0, x: 40 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.7 }}
            viewport={{ once: true }}
            className='space-y-8'
          >
            <div
              className='
                bg-[#F4EFE7]
                border-l-4
                border-[#C89A3E]
                p-6
              '
            >
              <p
                className='
                  italic
                  font-serif
                  text-[#3E3E3E]
                  text-lg
                  leading-8
                '
              >
                "Data centers have been seen as a huge boost to property tax
                revenues for cities and towns where they're appropriately
                sited."
              </p>
            </div>

            <p className='text-sm italic text-[#7A7A7A]'>
              — ElectriCities of North Carolina
            </p>

            <div
              className='
                bg-[#F4EFE7]
                border-l-4
                border-[#C89A3E]
                p-6
              '
            >
              <p
                className='
                  italic
                  font-serif
                  text-[#3E3E3E]
                  text-lg
                  leading-8
                '
              >
                "It will enhance our tax base significantly, and it won't be a
                heavy lift for our community."
              </p>
            </div>

            <p className='text-sm italic text-[#7A7A7A]'>
              — North Carolina local official, Business North Carolina, 2025
            </p>
          </motion.div>
        </div>
      </div>
    </section>
  )
}
